```{r}

stringsAsFactors = F
titration <- read.table("~/Desktop/fit_data.txt", header = T, fill = TRUE)

sigmoid <- function(x){
  GFP.OD = exp(x)/(1+exp(x))
}

ggplot(filter(titration, Architecture == 'COMBO'), aes(x = log10(Concentration), y = log2(GFP.OD))) + geom_smooth() + geom_point(aes(color = 'red'))

fitmodel <- nls(log2(titration$GFP.OD)~a/(1 + exp(-b * (log10(titration$Concentration-c)))), start=list(a=20,b=.5,c=25))


```

```{r}
background <- read.table("~/Desktop/InducibleArchitectures/raw_data/background_gfp.txt", header = T, fill = TRUE)

g <- background %>%
  ggplot(aes(x = OD, y = GFP)) + geom_point(aes(color = Run)) + geom_smooth(method = 'lm', aes(color = Run))

background %>%
  ggplot(aes(x = OD, y = GFP)) + geom_point(aes(color = Run)) + geom_smooth(method = 'lm', aes(color = Run)) + facet_wrap(~Run, scales = 'free')

plot_grid(g, b)

# Using Run C, GFP = 514.76(OD) + 40.378
titration <- read.table("~/Desktop/InducibleArchitectures/raw_data/titration.txt", header = T, fill = TRUE)

test <- titration %>% 
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) 

  ungroup() %>%
  ggplot(aes(x=log10(Concentration), y=avg_GFP.OD, colour = Architecture)) + geom_point() + geom_line() + facet_wrap(~Architecture, ncol = 2)

```


```{r}
# COMBO
tit1 <- titration %>% 
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
    group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(SEM = sd(GFP.OD)/sqrt(n())) %>%
    ungroup() %>%
    filter(Architecture == 'C1' | Architecture == 'C2' | Architecture == 'UV5' | Architecture == 'N') %>%
    ggplot(aes(x=log10(Concentration), y=avg_GFP.OD, colour = Architecture, linetype = Architecture)) +
    geom_errorbar(aes(ymin=avg_GFP.OD-SEM, ymax=avg_GFP.OD+SEM), width=.1, linetype = 'solid', color = 'black') +
    geom_point(size = 3, alpha = 0.75) +
  geom_line() + 
  scale_linetype_manual(values = c("solid", "solid", "dashed", "solid")) +
  scale_color_manual(values = c("#EE2524", "#FEA3A3", "black", "grey50")) +
  labs(y = expression('GFP/OD'), x = expression('log'[10]~'(mM IPTG)')) +
  theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

# MULTIPLE
tit2 <- titration %>% 
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(SEM = sd(GFP.OD)/sqrt(n())) %>%
  ungroup() %>%
  filter(Architecture == 'M1' | Architecture == 'M2' | Architecture == 'UV5' | Architecture == 'N') %>%
  ggplot(aes(x=log10(Concentration), y=avg_GFP.OD, colour = Architecture, linetype = Architecture)) +
    geom_errorbar(aes(ymin=avg_GFP.OD-SEM, ymax=avg_GFP.OD+SEM), width=.1, linetype = 'solid', color = 'black') +
geom_point(size = 3, alpha = 0.75) + geom_line() +
  scale_linetype_manual(values = c("solid", "solid", "dashed", "solid")) +
  scale_color_manual(values = c("#3B9BB3", "#7CDFFF", "black", "grey50")) +
  labs(y = expression('GFP/OD'), x = expression('log'[10]~'(mM IPTG)')) +
    theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

# DISTAL
tit3 <- titration %>% 
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(SEM = sd(GFP.OD)/sqrt(n())) %>%
  ungroup() %>%
  filter(Architecture == 'D1' | Architecture == 'D2' | Architecture == 'UV5' | Architecture == 'N') %>%
  ggplot(aes(x=log10(Concentration), y=avg_GFP.OD, colour = Architecture, linetype = Architecture)) +
  geom_errorbar(aes(ymin=avg_GFP.OD-SEM, ymax=avg_GFP.OD+SEM), width=.1, linetype = 'solid', color = 'black') +
geom_point(size = 3, alpha = 0.75) + geom_line() +
    scale_linetype_manual(values = c("solid", "solid", "dashed", "solid")) +
  scale_color_manual(values = c("#EBCC2A", "#FFE77C", "black", "grey50")) +
  labs(y = expression('GFP/OD'), x = expression('log'[10]~'(mM IPTG)')) +
    theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

# STERIC
tit4 <- titration %>% 
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(SEM = sd(GFP.OD)/sqrt(n())) %>%
  ungroup() %>%
  filter(Architecture == 'S1' | Architecture == 'S2' | Architecture == 'UV5' | Architecture == 'N') %>%
  ggplot(aes(x=log10(Concentration), y=avg_GFP.OD, colour = Architecture, linetype = Architecture)) +
    geom_errorbar(aes(ymin=avg_GFP.OD-SEM, ymax=avg_GFP.OD+SEM), width=.1, linetype = 'solid', color = 'black') + geom_point(size = 3, alpha = 0.75) + geom_line() +
  scale_linetype_manual(values = c("dashed", "solid", "solid", "solid")) +
  scale_color_manual(values = c("black", "#5D478B", "#B19CD9", "grey50")) +
  labs(y = expression('GFP/OD'), x = expression('log'[10]~'(mM IPTG)')) +
    theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

plot_grid(tit1, tit2, tit3, tit4, ncol = 2, labels = c('A', 'B', 'C', 'D'), label_size = 20)
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_PRCurves.pdf', width = 10, height = 7)

```


```{r}
# Calculate FC value

PRFC <- titration %>%
  mutate(background = 514.76*OD + 40.378) %>%
  mutate(normalized_GFP = GFP - background) %>%
  mutate(GFP.OD = normalized_GFP/OD) %>%
  filter(GFP.OD > 0, Concentration == 1e-04 | Concentration == 1e+00) %>%
  group_by(Architecture, Concentration) %>%
  mutate(avg_GFP.OD = mean(GFP.OD)) %>%
  ungroup() %>%
  select(Architecture, Concentration, avg_GFP.OD) %>%
  group_by(Architecture, Concentration) %>%
  mutate(row_id=1:n()) %>% 
  ungroup() %>%
  spread(Concentration, avg_GFP.OD) %>%
  select(-row_id) %>%
  group_by(Architecture) %>%
  mutate(FC = `1`/`1e-04`) %>%
  ungroup() %>%
  unique() %>%
  select(Architecture, FC) %>%
  na.omit()

write.csv(PRFC, '~/Desktop/InducibleArchitectures/processed_data/plateReaderFC.csv')
```














