```{r setup}
knitr::opts_knit$set(root.dir = '../processed_data')
```

```{r, include = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(viridis)
require(cowplot)
theme_set(theme_cowplot())
require(forcats)
library(ggsignif)
```

```{r}
# read in master data frame
induce_exp <- read.table("../processed_data/LacZ_variant_exp.txt", header = T)

# split reg elements apart
induce_combo <- subset(induce_exp, grepl("COMBO", induce_exp$name)) %>% separate(col = 'name', into = c("Library", "Distal", "Min_35", "Min_10", "Proximal"), sep = "-", remove = F)

# save data table for input
write.table(induce_combo, '../processed_data/data_tables/Figure2.txt')
```

```{r}
# Figure 2B: Big tile plot of uninduced expression
induce_combo$Min_10  <- with(induce_combo, reorder(Min_10, normalized_RNA_exp_Induced_12, median))
induce_combo$Min_35 <- with(induce_combo, reorder(Min_35, -normalized_RNA_exp_Induced_12, median))

ggplot(induce_combo, aes(x = Proximal, y = Distal)) + 
  geom_tile(aes(fill = log2(normalized_RNA_exp_UnInduced_12)), alpha = 1, size = 0.5, color = 'gray20') + 
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_fill_viridis(name ='log2(unid)', limits = c(-1.82, 6.245)) +
  facet_grid(Min_35 ~ Min_10) +
  theme(panel.background = element_rect(fill = "gray40"), 
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(), 
        axis.text.x = element_blank(), 
        strip.text = element_blank(),
        panel.spacing = unit(0.10, "lines"))
ggsave('../Figure2/Figure2B.pdf', height = 11, width = 13)
```

```{r}
# Figure 2C: Tile plot of Distal x Proximal for consensus promoter, fill is Uninduced Expression. 
ggplot(filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons'), aes(x = Proximal, y = Distal)) + geom_tile(aes(fill = log2(normalized_RNA_exp_UnInduced_12)), color = 'black', alpha = 0.9, size = 0.25) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  scale_fill_viridis(name = expression('log'[2]~'(Uninduced Expression)'), limits = c(-1.82, 6.245)) +
  labs(x = 'Proximal', y = 'Distal', size = 20) +
  theme(panel.background = element_rect(fill = "gray40")) +
  theme(axis.text=element_text(size=14), axis.title=element_text(size = 14)) +
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size = 15))
ggsave('../Figure2/Figure2C.pdf', width = 12, height = 7)
```

```{r}
# Figure 2D: Big tile plot of fold-change
induce_combo$Min_10  <- with(induce_combo, reorder(Min_10, normalized_RNA_exp_Induced_12, median))
induce_combo$Min_35 <- with(induce_combo, reorder(Min_35, -normalized_RNA_exp_Induced_12, median))

ggplot(induce_combo, aes(x = Proximal, y = Distal)) + 
  geom_tile(aes(fill = log2(ratio)), alpha = 1, size = 0.5, color = 'gray20') + 
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_fill_viridis(limits = c(-2.2, 3.17)) +
  facet_grid(Min_35 ~ Min_10) +
  theme(panel.background = element_rect(fill = "gray40"), 
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(), 
        axis.text.x = element_blank(), 
        strip.text = element_blank(),
        panel.spacing = unit(0.10, "lines"))
ggsave('../Figure2/Figure2D.pdf', height = 11, width = 13)
```


```{r}
# Figure 2E: Tile plot of Distal x Proximal for consensus promoter, fill is Fold Change. 
ggplot(filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons'), aes(x = Proximal, y = Distal)) + geom_tile(aes(fill = log2(ratio)), color = 'black', alpha = 0.9, size = 0.25) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  scale_fill_viridis(name = expression('log'[2]~'(Fold-change)'), limits = c(-2.2, 3.17)) +
  labs(x = 'Proximal', y = 'Distal', size = 20) +
  theme(panel.background = element_rect(fill = "gray40")) +
  theme(axis.text=element_text(size=14), axis.title=element_text(size = 14)) +
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size = 15))
ggsave('../Figure2/Figure2E.pdf', width = 10.5, height = 7)
```

```{r}
# small calculations

# 1. range of uninduced expression of library
max(induce_combo$normalized_RNA_exp_UnInduced_12)/min(induce_combo$normalized_RNA_exp_UnInduced_12)

# 2. range of uninduced expression for each core promoter
induce_combo %>%
  group_by(Min_10, Min_35) %>%
  mutate(min_unind = min(normalized_RNA_exp_UnInduced_12),
         max_unind = max(normalized_RNA_exp_UnInduced_12),
         range = max_unind/min_unind) %>%
  ungroup() %>%
  select(Min_10, Min_35, range) %>%
  distinct()

# 3. For consensus core promoter, is proximal O1/Osym largely deterministic of fold-change?
# fold-difference
group1 = filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym' | Proximal == 'lacO1') %>%
  mutate(avg_fc = mean(ratio)) %>% select(avg_fc) %>% distinct()
group2 = filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons', !(Proximal == 'lacOsym' | Proximal == 'lacO1')) %>% mutate(avg_fc = mean(ratio)) %>% select(avg_fc) %>% distinct()
group1[,1]/group2[,1] # fold-difference is 4.61

# T-test
group1 = filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym' | Proximal == 'lacO1')
group2 = filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons', !(Proximal == 'lacOsym' | Proximal == 'lacO1'))
t.test(group1$ratio, group2$ratio) # Welch two-sample t-test, p-value = 1.44e-06

# 4. how low was uninduced expression for weak core promoters?
induce_combo %>%
  group_by(Min_10, Min_35) %>%
  mutate(median_unind = median(normalized_RNA_exp_UnInduced_12),
         avg_unind = mean(normalized_RNA_exp_UnInduced_12)) %>%
  ungroup() %>%
  select(Min_10, Min_35, median_unind, avg_unind) %>%
  distinct()

# fold-change of consensus/proxOsym/distalOsym vs. consensus/proxOsym/distalO3
induce_combo %>% filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym', Distal == 'lacOsym') %>%
  select(ratio)
induce_combo %>% filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym', Distal == 'lacO3') %>%
  select(ratio)

# fold-change of consensus/proxOsym/distalOsym vs. consensus/proxO1/distalOsym
induce_combo %>% filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym', Distal == 'lacOsym') %>%
  select(ratio, normalized_RNA_exp_UnInduced_12, normalized_RNA_exp_Induced_12)
induce_combo %>% filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacO1', Distal == 'lacOsym') %>%
  select(ratio, normalized_RNA_exp_UnInduced_12, normalized_RNA_exp_Induced_12)

1.463874
2.58448

6.771608
23.19362	
# how much lower is the induced expression of consensus/proxOsym/distalOsym vs. consensus/proxOsym/distalO3 
base = filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym', Distal == 'lacOsym')$normalized_RNA_exp_Induced_12

test = induce_combo %>% 
  filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym') %>%
  mutate(rel_induced_exp = normalized_RNA_exp_Induced_12/base) %>%
  mutate(avg = mean(rel_induced_exp))

induce_combo %>% filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons', Proximal == 'lacOsym', Distal == 'lacO3') %>%
  select(normalized_RNA_exp_Induced_12)
37.63329/6.771608

```








