---
title: "R Notebook"
output: html_notebook
---
```{r}
#library(RColorBrewer)
#library(dplyr)
induce_exp <- read.table("~/Desktop/InducibleArchitectures/processed_data/induce_exp(updated).txt", header = T)

induce_combo <- subset(induce_exp, grepl("COMBO", induce_exp$name)) %>% separate(col = 'name', into = c("Library", "Distal", "Min_35", "Min_10", "Proximal"), sep = "-", remove = F)
induce_distal <- subset(induce_exp, grepl("DISTAL", induce_exp$name)) %>% separate(col = 'name', into = c("Library", "Distal", "Offset", "Min_35", "Core", "Min_10"), sep = "-", remove = F)

induce_distal$Min_35 <- with(induce_distal, reorder(Min_35, ratio, median))
induce_distal$Min_10 <- with(induce_distal, reorder(Min_10, ratio, median))
induce_distal$Core <- with(induce_distal, reorder(Core, ratio, median))
induce_distal$Distal <- with(induce_distal, reorder(Distal, ratio, median))
induce_distal$Core <- gsub("_core", "", induce_distal$Core)

induce_steric <- subset(induce_exp, grepl("STERIC", induce_exp$name)) %>% 
  separate(col = 'name', into = c("Library", "Loop_Distance", "UP", "Core", "Extended_Min_10", "Min_10", "Proximal"), sep = "-", remove = F)
induce_steric$Min_10 <- with(induce_steric, reorder(Min_10, ratio, median))
induce_steric$Core <- with(induce_steric, reorder(Core, ratio, median))
induce_steric$Proximal <- with(induce_steric, reorder(Proximal, ratio, median))

induce_multiple <- subset(induce_exp, grepl("MULTIPLE", induce_exp$name)) %>% separate(col = 'name', into = c("Library", "Distal_left", "Distal_right", "Min_35", "Min_10", "Proximal"), sep = "-", remove = F) %>% mutate(induction = ratio/normalized_RNA_exp_UnInduced_12)

```


```{r}
# FIGURE SX: PCombo supplement - Presence of Osym in both distal and proximal sites drove lower expression at 1 mM IPTG than promoters with combinations of Osym and O1
filler <- c("midnightblue", "orange") 
t1 <- induce_combo %>%
  filter(Distal == 'lacOsym', (Proximal == 'lacO1' | Proximal == 'lacOsym'), Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>%
  ggplot(aes(x = Proximal, y = normalized_RNA_exp_Induced_12)) + 
  geom_bar(stat = 'identity', fill = filler, color = 'black', alpha = 0.9) + ylab("Induced Expression")
t2 <- induce_combo %>%
  filter(Distal == 'lacOsym', Proximal == 'lacO1' | Proximal == 'lacOsym', Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>%
  ggplot(aes(x = Proximal, y = normalized_RNA_exp_UnInduced_12)) + 
  geom_bar(stat = 'identity', fill = filler, color = 'black', alpha = 0.9) + ylab("Uninduced Expression")
plot_grid(t1, t2) 
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureS1.pdf', height = 6, width = 8)
```

```{r}
# FIGURE SX: Pcombo supplement - for 2F

induce_combo %>%
  filter(Proximal == 'lacOsym' | Proximal == 'lacO1') %>%
  mutate(min10min35_combo = paste(Min_10, '+', Min_35)) %>%
  ggplot(aes(x = min10min35_combo, y = normalized_RNA_exp_UnInduced_12)) + geom_boxplot(outlier.shape = NA, aes(fill = min10min35_combo), alpha = 0.6) + 
  geom_jitter(aes(fill = min10min35_combo), pch = 21, color = 'black', size = 4) + 
  scale_fill_viridis(discrete=TRUE)
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureS_combo.pdf', height = 5, width = 10)
```

```{r} 
# FIGURE SX: Pmultiple supplement - Induced/Uninduced comparison with Pcombo heatmap
colnames(induce_combo)[colnames(induce_combo) == "Distal"] <- "Distal_right"
combo_multiple_comp <- left_join(induce_combo, induce_multiple, by = c("Distal_right", 'Min_10', "Min_35", "Proximal"))
combo_multiple_comp <- combo_multiple_comp[complete.cases(combo_multiple_comp), ] %>% filter(Min_10 == 'minus10cons' & Min_35 == 'minus35cons') # remove NA ones

test <- combo_multiple_comp %>% 
  filter(Proximal == 'lacOsym' | Proximal == 'lacO1') %>%
  group_by(Distal_left, Distal_right) %>%
  dplyr::mutate(mean_diff = mean(normalized_RNA_exp_UnInduced_12.y/normalized_RNA_exp_UnInduced_12.x))



induced <- combo_multiple_comp %>% 
  filter(Proximal == 'lacOsym' | Proximal == 'lacO1') %>%
  group_by(Distal_left, Distal_right) %>%
  dplyr::mutate(mean_diff = mean(normalized_RNA_exp_Induced_12.y/normalized_RNA_exp_Induced_12.x)) %>%
  ungroup() %>%
  ggplot(., aes(x = Distal_right, y = Distal_left)) + geom_tile(aes(fill = mean_diff), alpha = 1, color = 'black', size = 0.4) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  scale_fill_viridis(name = 'Fold-change', na.value = 'gray20', limits = c(0.14, 3.15)) +
  #scale_fill_distiller(palette = 'RdBu', na.value = 'gray20', name = 'Change in Induced_Exp', limits = c(0.3, 1.7)) +
  scale_x_discrete(limits = c("lacOscram", "lacO3", 'lacO2', 'lacO1', 'lacOsym')) + scale_y_discrete(limits = c("lacOscram", "lacO3", 'lacO2', 'lacO1', 'lacOsym')) + labs(x = 'Canonical Distal', y = 'Additional Distal', size = 20) +
geom_text(aes(label=signif(mean_diff, 3)), size=5) +
  theme(axis.text = element_text(size = 20),
         axis.title = element_text(size = 20),
         title = element_text(size = 24),
         legend.text = element_text(size = 14))
uninduced <- combo_multiple_comp %>% 
  filter(Proximal == 'lacOsym' | Proximal == 'lacO1') %>%
  group_by(Distal_left, Distal_right) %>%
  dplyr::mutate(mean_diff = mean(normalized_RNA_exp_UnInduced_12.y/normalized_RNA_exp_UnInduced_12.x)) %>%
  ungroup() %>%
  ggplot(., aes(x = Distal_right, y = Distal_left)) + geom_tile(aes(fill = mean_diff), alpha = 1, color = 'black', size = 0.4) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  scale_fill_viridis(name = 'Fold-change', na.value = 'gray20', limits = c(0.14, 3.15)) +
  #scale_fill_distiller(palette = 'RdBu', na.value = 'gray20', name = 'Change in Uninduced_Exp', limits = c(-0.842, 2.842)) +
  scale_x_discrete(limits = c("lacOscram", "lacO3", 'lacO2', 'lacO1', 'lacOsym')) + scale_y_discrete(limits = c("lacOscram", "lacO3", 'lacO2', 'lacO1', 'lacOsym')) + labs(x = 'Canonical Distal', y = 'Additional Distal', size = 20) +
geom_text(aes(label=signif(mean_diff, 3)), size=5) +
  theme(axis.text = element_text(size = 20),
         axis.title = element_text(size = 20),
         title = element_text(size = 24),
         legend.text = element_text(size = 14))

plot_grid(induced, uninduced, ncol = 2)
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_Multiple.pdf', width = 24, height = 8)
```

```{r}
#PCore supplement - consistent and strong repression across all pairs of core and distal operators
distal_scram_exp <- filter(induce_distal, Core == 'lacOscram', Distal == 'lacOscram', Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>% dplyr::select(Offset, ratio)
distal_comp <- left_join(induce_distal, distal_scram_exp, by = 'Offset') %>%
  filter(Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>%
  dplyr::mutate(norm_ratio = ratio.x/ratio.y) %>%
  dplyr::select(Library, Core, Distal, Offset, norm_ratio) %>%
  unique(.)
distal_comp <- distal_comp[!is.na(distal_comp$norm_ratio),]
distal_comp$Distal <- factor(distal_comp$Distal, levels = c('lacOscram','lacO3','lacO2','lacO1','lacOsym'))

ggplot(distal_comp, aes(y = log2(norm_ratio), fill = Distal, x = Core)) + 
  geom_bar(position = "dodge", stat = 'identity', color = 'black') + 
  scale_x_discrete(limits = c('lacOscram', 'lacO3', 'lacO2', 'lacO1', 'lacOsym')) +
  scale_fill_viridis(discrete = TRUE, name = 'Distal site', alpha = 0.9) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  labs(x = 'Core site', y = expression('log'[2]~'(Normalized Fold Induction)')) + geom_hline(yintercept=0, color = 'black', size = 0.5) + geom_hline(yintercept=2, linetype = 'dashed', color = 'red', size = 0.5) + geom_hline(yintercept=4, linetype = 'dashed', color = 'red', size = 0.5) +   
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size = 20)) +
  facet_wrap(~Offset, scales = 'free')
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_Distal.pdf', width = 20, height = 18)
```

```{r}
# Psteric supplement - Although weak, if any, transcription was detected from promoters with only a -10, we found that relatively strong promoters could be created by the addition of an UP-element and extended -10 
up_326x_ext_10 <- filter(induce_steric, Loop_Distance == 55, UP == 'up_326x', Extended_Min_10 == 'ext_min10') %>% mutate(category = 'up_326x_ext_10') 
up_326x_ext_UV5 <- filter(induce_steric, Loop_Distance == 55, UP == 'up_326x', Extended_Min_10 == 'ext_UV5') %>% mutate(category = 'up_326x_ext_UV5')
no_up_ext_10 <- filter(induce_steric, Loop_Distance == 55, UP == 'no_up', Extended_Min_10 == 'ext_min10') %>% mutate(category = 'no_up_ext_10')
no_up_ext_UV5 <- filter(induce_steric, Loop_Distance == 55, UP == 'no_up', Extended_Min_10 == 'ext_UV5') %>% mutate(category = 'no_up_ext_UV5')
temp1 <- rbind(up_326x_ext_10, up_326x_ext_UV5)
temp2 <- rbind(temp1, no_up_ext_10)
steric_box <- rbind(temp2, no_up_ext_UV5)
rm(temp1, temp2, up_326x_ext_10, up_326x_ext_UV5, no_up_ext_10, no_up_ext_UV5)
pal4 <- brewer.pal(n=4, name ='RdBu')

steric_box %>%
  filter(Proximal == 'lacOscram', Core == 'lacOscram') %>%
  ggplot(., aes(fill = Min_10, y = normalized_RNA_exp_UnInduced_12, x = category)) +
  geom_bar(position = 'dodge', stat = 'identity', alpha = 0.9, color = 'black') + scale_x_discrete(limits = c('no_up_ext_UV5', 'up_326x_ext_UV5', 'no_up_ext_10', 'up_326x_ext_10')) +   scale_fill_manual(values = pal4) + labs(y = 'Uninduced expression', x = 'Regulatory element combination') + theme(axis.text.x = element_text(angle = 45, hjust = 1, size =10)) + 
    theme(axis.text = element_text(size = 20),
         axis.title = element_text(size = 20),
         title = element_text(size = 24),
         legend.text = element_text(size = 15))
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_Steric1.pdf', width = 10, height = 7)
```

```{r}
# Psteric supplement - We find that variants constructed with proximal operator sites located 15 bp downstream of the TSS are generally more inducible
induce_steric %>%
  ggplot(aes(x=Loop_Distance, y=ratio)) +
  geom_jitter(aes(fill = Loop_Distance), pch=21, color='black',alpha=0.75, size=4) +
  geom_boxplot(outlier.shape=NA, fill = NA) + 
  geom_hline(yintercept=4.5,color='firebrick',linetype='dashed', size=1) +
  scale_fill_manual(values=c("darkslateblue", "#de6fa1")) +
  labs(y = 'Fold-change', x = 'Loop distance')
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_Steric2.pdf', width = 7, height = 5)
```

```{r}
# Psteric supplement - we found that expression of these promoters only occurred when particular core operator sites were used
induce_steric %>%
  filter(UP == 'up_326x' | UP == 'up_136x') %>%
  filter(Loop_Distance == 55) %>%
  filter(Extended_Min_10 == 'ext_min10') %>%
  filter(Min_10 == 'minus10cons') %>%
  ggplot(aes(x=Proximal, y=Core)) + geom_tile(aes(fill=log2(normalized_RNA_exp_UnInduced_12)), alpha = 0.9, color = 'black') + 
  scale_fill_viridis() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15))
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_Steric3.pdf', width = 10, height = 5)
```
```{r}
# Plate reader supplement with titration profiles of selected promoters
titration <- read.table("~/Desktop/InducibleArchitectures/raw_data/titration.txt", header = T, fill = TRUE)

# COMBO
uninduced <- titration %>% filter(Concentration == '1e-04') %>% mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
    group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    ungroup() %>%
    select(Architecture, avg_GFP.OD) %>% distinct()
UV5_unind <- filter(uninduced, Architecture == 'UV5')$avg_GFP.OD  
N_unind <- filter(uninduced, Architecture == 'N')$avg_GFP.OD  

C1_unind <- filter(uninduced, Architecture == 'C1')$avg_GFP.OD  
C2_unind <- filter(uninduced, Architecture == 'C2')$avg_GFP.OD  
tit1 <-titration %>% 
    filter(Architecture == 'C1' | Architecture == 'C2' | Architecture == 'UV5' | Architecture == 'N') %>%
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
    group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(FC = ifelse(Architecture == 'C1', avg_GFP.OD/C1_unind, 
                ifelse(Architecture == 'C2', avg_GFP.OD/C2_unind,
                ifelse(Architecture == 'UV5', avg_GFP.OD/UV5_unind, avg_GFP.OD/N_unind)))) %>%
    mutate(SEM = sd(FC)/sqrt(n())) %>%
    ungroup() %>%
    ggplot(aes(x=log10(Concentration), y=FC, colour = Architecture, linetype = Architecture)) +
    geom_errorbar(aes(ymin=FC-SEM, ymax=FC+SEM), width=.1, linetype = 'solid', color = 'black') +
    geom_point(size = 3, alpha = 0.75) +
  geom_line() + 
  scale_linetype_manual(values = c("solid", "solid", "dashed", "solid")) +
  scale_color_manual(values = c("#EE2524", "#FEA3A3", "black", "grey50")) +
  labs(y = expression('FC'), x = expression('log'[10]~'(mM IPTG)')) +
  theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

# MULTIPLE
M1_unind <- filter(uninduced, Architecture == 'M1')$avg_GFP.OD  
M2_unind <- filter(uninduced, Architecture == 'M2')$avg_GFP.OD  
tit2 <- titration %>% 
    filter(Architecture == 'M1' | Architecture == 'M2' | Architecture == 'UV5' | Architecture == 'N') %>%
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(FC = ifelse(Architecture == 'M1', avg_GFP.OD/M1_unind, 
                ifelse(Architecture == 'M2', avg_GFP.OD/M2_unind,
                ifelse(Architecture == 'UV5', avg_GFP.OD/UV5_unind, avg_GFP.OD/N_unind)))) %>%
    mutate(SEM = sd(FC)/sqrt(n())) %>%
  ungroup() %>%
  ggplot(aes(x=log10(Concentration), y=FC, colour = Architecture, linetype = Architecture)) +
    geom_errorbar(aes(ymin=FC-SEM, ymax=FC+SEM), width=.1, linetype = 'solid', color = 'black') +
geom_point(size = 3, alpha = 0.75) + geom_line() +
  scale_linetype_manual(values = c("solid", "solid", "dashed", "solid")) +
  scale_color_manual(values = c("#3B9BB3", "#7CDFFF", "black", "grey50")) +
  labs(y = expression('FC'), x = expression('log'[10]~'(mM IPTG)')) +
    theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

# DISTAL
D1_unind <- filter(uninduced, Architecture == 'D1')$avg_GFP.OD  
D2_unind <- filter(uninduced, Architecture == 'D2')$avg_GFP.OD  
tit3 <- titration %>% 
    filter(Architecture == 'D1' | Architecture == 'D2' | Architecture == 'UV5' | Architecture == 'N') %>%
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
    mutate(avg_GFP.OD = mean(GFP.OD)) %>%
    mutate(FC = ifelse(Architecture == 'D1', avg_GFP.OD/D1_unind, 
                ifelse(Architecture == 'D2', avg_GFP.OD/D2_unind,
                ifelse(Architecture == 'UV5', avg_GFP.OD/UV5_unind, avg_GFP.OD/N_unind)))) %>%
    mutate(SEM = sd(FC)/sqrt(n())) %>%
  ungroup() %>%
  ggplot(aes(x=log10(Concentration), y=FC, colour = Architecture, linetype = Architecture)) +
  geom_errorbar(aes(ymin=FC-SEM, ymax=FC+SEM), width=.1, linetype = 'solid', color = 'black') +
geom_point(size = 3, alpha = 0.75) + geom_line() +
    scale_linetype_manual(values = c("solid", "solid", "dashed", "solid")) +
  scale_color_manual(values = c("#EBCC2A", "#FFE77C", "black", "grey50")) +
  labs(y = expression('FC'), x = expression('log'[10]~'(mM IPTG)')) +
    theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

# STERIC
S1_unind <- filter(uninduced, Architecture == 'S1')$avg_GFP.OD  
S2_unind <- filter(uninduced, Architecture == 'S2')$avg_GFP.OD  
tit4 <- titration %>% 
    filter(Architecture == 'S1' | Architecture == 'S2' | Architecture == 'UV5' | Architecture == 'N') %>%
    mutate(background = 514.76*OD + 40.378) %>%
    mutate(normalized_GFP = GFP - background) %>%
    mutate(GFP.OD = normalized_GFP/OD) %>%
    filter(GFP.OD > 0) %>%
  group_by(Architecture, Concentration) %>%
  mutate(avg_GFP.OD = mean(GFP.OD)) %>%
  mutate(FC = ifelse(Architecture == 'S1', avg_GFP.OD/S1_unind, 
                ifelse(Architecture == 'S2', avg_GFP.OD/S2_unind,
                ifelse(Architecture == 'UV5', avg_GFP.OD/UV5_unind, avg_GFP.OD/N_unind)))) %>%
  mutate(SEM = sd(FC)/sqrt(n())) %>%
  ungroup() %>%
  ggplot(aes(x=log10(Concentration), y=FC, colour = Architecture, linetype = Architecture)) +
    geom_errorbar(aes(ymin=FC-SEM, ymax=FC+SEM), width=.1, linetype = 'solid', color = 'black') + geom_point(size = 3, alpha = 0.75) + geom_line() +
  scale_linetype_manual(values = c("dashed", "solid", "solid", "solid")) +
  scale_color_manual(values = c("black", "#5D478B", "#B19CD9", "grey50")) +
  labs(y = expression('FC'), x = expression('log'[10]~'(mM IPTG)')) +
    theme(axis.text = element_text(size = 16),
         axis.title = element_text(size = 20),
         legend.text = element_text(size = 15))

plot_grid(tit1, tit2, tit3, tit4, ncol = 2, labels = c('A', 'B', 'C', 'D'), label_size = 20)
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_PRCurves.pdf', width = 10, height = 7)
```

```{r}
# Correlation between each of the FC measuring methods
PRFC <- titration %>%
  mutate(background = 514.76*OD + 40.378) %>%
  mutate(normalized_GFP = GFP - background) %>%
  mutate(GFP.OD = normalized_GFP/OD) %>%
  filter(GFP.OD > 0, Concentration == 1e-04 | Concentration == 1e+00) %>%
  group_by(Architecture, Concentration) %>%
  mutate(avg_GFP.OD = mean(GFP.OD)) %>%
  ungroup() %>%
  select(Architecture, Concentration, avg_GFP.OD) %>%
  group_by(Architecture, Concentration) %>%
  mutate(row_id=1:n()) %>% 
  ungroup() %>%
  spread(Concentration, avg_GFP.OD) %>%
  select(-row_id) %>%
  group_by(Architecture) %>%
  mutate(FC = `1`/`1e-04`) %>%
  ungroup() %>%
  unique() %>%
  select(Architecture, FC) %>%
  na.omit()
write.csv(PRFC, '~/Desktop/InducibleArchitectures/processed_data/plateReaderFC.csv')

FC_corr <- read.table('~/Desktop/InducibleArchitectures/processed_data/FC_corr.txt', sep = '\t', header = TRUE)
FC_corr <- FC_corr[ , !names(FC_corr) %in% c("Abbreviation", "Variant.Name")]
ggpairs(FC_corr, columnLabels = c("FACS", "RNA-seq", "Plate Reader"), lower = list(
    continuous = "smooth"))
ggsave('~/Desktop/InducibleArchitectures/FigureSX/FigureSX_assayCorr.pdf', height = 6, width = 9)
```
```{r}
# Figure 2 Supplement: Optimal repressor changes by promoter
a1 <- ggplot(filter(induce_combo, Min_10 == 'minus10cons', Min_35 == 'minus35_31A_32C'), aes(x = Proximal, y = Distal)) + geom_tile(aes(fill = log2(ratio)), color = 'black', alpha = 0.9, size = 0.25) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  scale_fill_viridis(name = expression('log'[2]~'(Fold-change)')) +
  labs(x = 'Proximal', y = 'Distal', title = 'Consensus -10 & Mutated -35 (31A,32C)', size = 20) +
  theme(panel.background = element_rect(fill = "gray40")) +
  theme(axis.text=element_text(size=14), axis.title=element_text(size = 14)) +
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size = 15))

a2 <-ggplot(filter(induce_combo, Min_10 == 'minus10_12G', Min_35 == 'minus35cons'), aes(x = Proximal, y = Distal)) + geom_tile(aes(fill = log2(ratio)), color = 'black', alpha = 0.9, size = 0.25) + theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 15), axis.text.y = element_text(size = 15)) +
  scale_fill_viridis(name = expression('log'[2]~'(Fold-change)')) +
  labs(x = 'Proximal', y = 'Distal', title = 'Mutated -10 (12G) & Consensus -35', size = 20) +
  theme(panel.background = element_rect(fill = "gray40")) +
  theme(axis.text=element_text(size=14), axis.title=element_text(size = 14)) +
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        title = element_text(size = 24),
        legend.text = element_text(size = 15))
plot_grid(a1, a2)
rm(a1,a2)
ggsave('~/Desktop/InducibleArchitectures/FreshFigs/Fig2_S1.pdf', height = 5, width = 16.5)
```

```{r}
# Figure 2 Supplement: Connected dotplots of induced vs. uninduced for Osym distal
induce_combo %>%
  filter(Proximal == 'lacOsym', Min_10 == 'minus10cons', Min_35 == 'minus35cons') %>%
  gather(Type, Expression, 'normalized_RNA_exp_Induced_12':'normalized_RNA_exp_UnInduced_12') %>%
  ggplot(aes(x = Distal, y = Expression)) + geom_line(color = 'black', size =1, alpha = 1) + geom_point(aes(fill = Type), pch = 21, color = 'black', size = 5) +
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym"))
ggsave('~/Desktop/InducibleArchitectures/FreshFigs/comboDotPlot.pdf', height = 5, width = 7)
```
```{r}
# Figure 4 Supplement: VIOLIN
rel_ops <- c('lacOsym', 'lacO1', 'lacO2', 'lacO3', 'lacOscram')
bind_rows(filter(induce_combo, Proximal %in% rel_ops & Distal %in% rel_ops), filter(induce_distal, Offset == 22)) %>%
  bind_rows(., induce_multiple) %>%
  bind_rows(., filter(induce_steric, Loop_Distance == 55)) %>%
  filter(log2(ratio) >= 1) %>%
  ggplot(aes(x = Library, y = log2(ratio))) + 
  scale_y_discrete(limits = c(1,2,3,4,5)) +
  geom_violin(aes(fill = Library), trim = FALSE, alpha = 1, lwd =0.75) + 
  geom_boxplot(width = 0.06, outlier.shape = NA, fill = 'white') +
  scale_fill_manual(values = c('#3b9bb3', '#75af4f', '#e39225', '#c13b41')) +
  labs(y = 'log2(Fold-change)') +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        title = element_text(size = 24),
        legend.position = 'none')
#ggsave('~/Desktop/InducibleArchitectures/Figure4/Figure4_new.pdf', height = 5, width = 8)
```

```{r}
induce_combo$Min_10  <- with(induce_combo, reorder(Min_10, normalized_RNA_exp_Induced_12, median))
induce_combo$Min_35 <- with(induce_combo, reorder(Min_35, -normalized_RNA_exp_Induced_12, median))

ggplot(induce_combo, aes(x = Proximal, y = Distal)) + 
  geom_tile(aes(fill = log2(normalized_RNA_exp_Induced_12)), alpha = 1, size = 0.5, color = 'gray20') + 
  scale_x_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_y_discrete(limits = c("lacOscram", "O3_leftSym", "lacO2", "O3_rightSym", "O1_rightSym", "O2_leftSym", "lacO3", "O2_rightSym", "lacO1", "lacOsym")) + 
  scale_fill_viridis() +
  facet_grid(Min_35 ~ Min_10) +
  theme(panel.background = element_rect(fill = "gray40"), 
        axis.ticks = element_blank(), 
        axis.text.y = element_blank(), 
        axis.text.x = element_blank(), 
        strip.text = element_blank(),
        panel.spacing = unit(0.10, "lines"))
```

```{r}
# Figure S4C
induce_distal$Min_10  <- with(induce_distal, reorder(Min_10, normalized_RNA_exp_Induced_12, median))
induce_distal$Min_35 <- with(induce_distal, reorder(Min_35, normalized_RNA_exp_Induced_12, median))

induce_distal %>%
  filter(Offset == 22) %>%
  group_by(Min_10,Min_35) %>%
  mutate(avgInd = mean(normalized_RNA_exp_Induced_12)) %>%
ggplot(aes(x = Min_10, y = Min_35)) +
  geom_tile(aes(fill = log2(avgInd)), alpha = 1, size = 0.5, color = 'gray20') + 
  scale_fill_viridis()

```

```{r}
# standard curve for scram-scram promoters in P-combo
scram_C <- induce_combo %>%
  filter(Proximal == 'lacOscram' & Distal == 'lacOscram')
scram_D <- induce_distal %>%
  filter(Core == 'lacOscram' & Distal == 'lacOscram')
scram_S <- induce_steric %>%
  filter(Core == 'lacOscram' & Proximal == 'lacOscram') 
scram_M <- induce_multiple %>%
  filter(Proximal == 'lacOscram' & Distal_right == 'lacOscram' & Distal_left == 'lacOscram')
temp <- bind_rows(scram_C, scram_D)
temp <- bind_rows(temp, scram_S)
temp <- bind_rows(temp, scram_M)

temp %>%
  ggplot(aes(x = normalized_RNA_exp_UnInduced_12, y = normalized_RNA_exp_Induced_12)) + geom_point(size=3, alpha = 0.6) +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed', color = 'red') +
  scale_x_continuous(limits = c(-1, 100), trans = 'log2') +
  scale_y_continuous(limits = c(-1, 100), trans = 'log2') +
  geom_hline(yintercept = c(4,8,16,32,64)) + geom_vline(xintercept= c(4,8,16,32,64))
```

```{r}
# flow and RNA comparison
# Figure 5 Correlation plot
comp <- read.table('~/Desktop/newFlowComparison.txt', header = TRUE)

rcorr(comp$RNAseq, comp$Flow, type = 'spearman')$r 
library_comp <- comp %>%
  mutate(Library = ifelse(grepl('C', comp$Name), 'C',
                   ifelse(grepl('D', comp$Name), 'D',
                   ifelse(grepl('M', comp$Name), 'M',
                   ifelse(grepl('S', comp$Name), 'S', 'N')))))
library_comp %>%
  ggplot(aes(x = RNAseq, y = Flow)) + geom_smooth(method=lm, color = 'black', se = FALSE) +
  geom_point(aes(color=Library), size = 5) +
  scale_color_manual(values = c('#76af51', '#3b9bb3', '#e39225', 'black', '#c13a41')) +
  labs(x = 'RNA-seq Fold-change', y = 'Flow Cytometry Fold-change')
ggsave('~/Desktop/InducibleArchitectures/FreshFigs/flowRNAcomp.pdf', height = 6, width = 7.5)
```









